### ISSUE TITLE
npm run watch error

### ISSUE THREAD

**Issue by nygosh** [Instaparser/instaparser.js#3]
npm install request --save 를 설치한 후
npm run watch  실행을 하면 아래와 같은 오류가 발생합니다.
(#2 소스 업데이트전에는 정상 실행됨)

```console
ERROR in ./~/request/lib/har.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\Lee\Desktop\instar\node_modules\request\lib 
@ ./~/request/lib/har.js 3:9-22
```

**Comment by JeffGuKang** [comment]
https://github.com/request/request/issues/1529

**Comment by JeffGuKang** [comment]
Considering use https://github.com/matthew-andrews/isomorphic-fetch.

**Comment by JeffGuKang** [comment]
We changed the module from `request` to `axios`.
